/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sesion;


import Accesso.Acceso;
import AdminGral.RegistroAdminGral;
import InterfazAdmin.InterfazAdmin;
import Joption.Joption;
import Joption.Joptionx;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JaviieR
 */
public class Login extends javax.swing.JFrame {
   Joption icon = new Joption();
   Joptionx save = new Joptionx(); 
   
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        bloquear();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ingreso de Accesso de Usuarios");
        setIconImage(new ImageIcon(getClass().getResource("imagenes/icon monitor pc.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("imagenes/wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    void cancelar(){
        contraseña.setText("");
        usuarioL.setSelectedIndex(0);
        
    }
        void bloquear(){
       invi.setVisible(false);
       admin.setVisible(false);
      
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioL = new javax.swing.JComboBox<>();
        contraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        invi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        reg = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioL.setBackground(new java.awt.Color(0, 0, 0));
        usuarioL.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        usuarioL.setForeground(new java.awt.Color(255, 255, 255));
        usuarioL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "ADMINISTRADOR", "INVITADO" }));
        usuarioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 204));
        contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO : ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA :");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/Lap.png"))); // NOI18N

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/entrar.png"))); // NOI18N
        admin.setText("Ingresar");
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 0, 0));
        cancelar.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/cancelar.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        invi.setBackground(new java.awt.Color(0, 0, 0));
        invi.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N
        invi.setForeground(new java.awt.Color(255, 255, 255));
        invi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/entrar.png"))); // NOI18N
        invi.setText("Ingresar");
        invi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(0, 0, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminGral/admin.png"))); // NOI18N
        jMenu1.setText("ADMINISTRADOR");
        jMenu1.setFocusPainted(true);
        jMenu1.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N

        reg.setBackground(new java.awt.Color(51, 51, 255));
        reg.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/icon monitor pc.png"))); // NOI18N
        reg.setText("Nuevo Registro");
        reg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jMenu1.add(reg);

        jMenuItem2.setBackground(new java.awt.Color(51, 51, 255));
        jMenuItem2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sesion/imagenes/salir.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(invi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(contraseña)
                            .addComponent(usuarioL, 0, 220, Short.MAX_VALUE))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usuarioL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        cancelar();
       
    }//GEN-LAST:event_cancelarActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
      if(usuarioL.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null,"Seleccione Un Tipo de Accesso!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
            if(contraseña.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Sin Contraseña!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
          Acceso ca=new Acceso();
          ca.acceso(usuarioL.getSelectedItem().toString(),contraseña.getText(),usuarioL.getSelectedItem().toString());
          InterfazAdmin.usuario.setText(usuarioL.getSelectedItem().toString().toUpperCase());
          InterfazAdmin.usuario.setText(usuarioL.getSelectedItem().toString().toUpperCase());
          this.dispose();
    }//GEN-LAST:event_adminActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      this.dispose();
      JOptionPane.showMessageDialog(null,"Sistema Finalizado","SCIEC",JOptionPane.INFORMATION_MESSAGE,icon);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        RegistroAdminGral re= new RegistroAdminGral();
        re.setVisible(true);
        reg.setVisible(false);
    }//GEN-LAST:event_regActionPerformed

    private void usuarioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLActionPerformed
        // TODO add your handling code here:
        int acceso=usuarioL.getSelectedIndex();
        if(acceso==1){
            invi.setVisible(false);
            admin.setVisible(true);

        }else{
             invi.setVisible(true);
            admin.setVisible(false);
      

        }    
    }//GEN-LAST:event_usuarioLActionPerformed

    private void inviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviActionPerformed
        // TODO add your handling code here:
         if(usuarioL.getSelectedItem().equals("")){
             JOptionPane.showMessageDialog(null,"Seleccione Un Tipo de Accesso!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
            if(contraseña.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Sin Contraseña!","ERROR",JOptionPane.ERROR_MESSAGE,save);
             return;        
              }
        
          
          Acceso ca=new Acceso();
          ca.accesoinvitado(usuarioL.getSelectedItem().toString(),contraseña.getText(),usuarioL.getSelectedItem().toString());
        
          InterfazAdmin.usuario.setText(usuarioL.getSelectedItem().toString().toUpperCase());
          InterfazAdmin.usuario.setText(usuarioL.getSelectedItem().toString().toUpperCase());
          this.dispose();
    }//GEN-LAST:event_inviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton cancelar;
    public static javax.swing.JPasswordField contraseña;
    private javax.swing.JButton invi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem reg;
    public static javax.swing.JComboBox<String> usuarioL;
    // End of variables declaration//GEN-END:variables
}
