/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actualizar;

import Conexion.Conexion;
import Joption.Joption;
import Joption.Joptionx;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JaviieR
 */
public class DatosEditarB extends javax.swing.JFrame {
      Joption icon = new Joption();
    Joptionx save = new Joptionx(); 

    /**
     * Creates new form DatosEditarB
     */
    public DatosEditarB() {
        initComponents();
          setTitle("Datos Usuarios");
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("actualizar.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("wall.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox();
        resolucion = new javax.swing.JLabel();
        cajaresolucion = new javax.swing.JTextField();
        tipoteclado = new javax.swing.JLabel();
        cajatipoteclado = new javax.swing.JTextField();
        hdmi = new javax.swing.JLabel();
        combohdmi = new javax.swing.JComboBox();
        combousb = new javax.swing.JComboBox();
        usb = new javax.swing.JLabel();
        cajaimpresora = new javax.swing.JTextField();
        impresora = new javax.swing.JLabel();
        cajaram = new javax.swing.JTextField();
        ram = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        cajadd = new javax.swing.JTextField();
        impresora1 = new javax.swing.JLabel();
        cajamarca = new javax.swing.JTextField();
        cajamodelo = new javax.swing.JTextField();
        impresora2 = new javax.swing.JLabel();
        cajapulgadas = new javax.swing.JTextField();
        pulgadas = new javax.swing.JLabel();
        lector = new javax.swing.JLabel();
        combolector = new javax.swing.JComboBox();
        impresora3 = new javax.swing.JLabel();
        cajaserie = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        sistemaoperativo = new javax.swing.JLabel();
        cajasistemaoperativo = new javax.swing.JTextField();
        marcaprocesador = new javax.swing.JLabel();
        cajamarcaprocesador = new javax.swing.JTextField();
        generacionprocesador = new javax.swing.JLabel();
        cajageneracionprocesador = new javax.swing.JTextField();
        marcatargrafica = new javax.swing.JLabel();
        cajamarcatargrafica = new javax.swing.JTextField();
        tipoups = new javax.swing.JLabel();
        cajatipoups = new javax.swing.JTextField();
        voltentrada = new javax.swing.JLabel();
        cajavoltentrada = new javax.swing.JTextField();
        voltsalida = new javax.swing.JLabel();
        cajavoltsalida = new javax.swing.JTextField();
        cantidadtomas = new javax.swing.JLabel();
        cajacantidadtomas = new javax.swing.JTextField();
        tipomouse = new javax.swing.JLabel();
        cajatipomouse = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ubicacion = new javax.swing.JLabel();
        cajaubicacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboestado = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        cajacustodio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajafecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Caracteristicas del Equipo ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14), java.awt.Color.white)); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Tipo de Equipo:");

        equipo.setBackground(new java.awt.Color(0, 102, 255));
        equipo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione--", "Impresora", "Cpu", "Laptop", "Servidor", "Scanner", "Proyector", "Monitor", "Ups", "Mouse", "Teclado" }));
        equipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoActionPerformed(evt);
            }
        });

        resolucion.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        resolucion.setForeground(new java.awt.Color(0, 51, 102));
        resolucion.setText("Resolucion :");

        cajaresolucion.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaresolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaresolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaresolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaresolucionActionPerformed(evt);
            }
        });

        tipoteclado.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        tipoteclado.setForeground(new java.awt.Color(0, 51, 102));
        tipoteclado.setText("Tipo teclado:");

        cajatipoteclado.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajatipoteclado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajatipoteclado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajatipoteclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatipotecladoActionPerformed(evt);
            }
        });

        hdmi.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        hdmi.setForeground(new java.awt.Color(0, 51, 102));
        hdmi.setText("Puerto HMDI :");

        combohdmi.setBackground(new java.awt.Color(0, 102, 255));
        combohdmi.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combohdmi.setForeground(new java.awt.Color(255, 255, 255));
        combohdmi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combohdmi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combohdmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combohdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combohdmiActionPerformed(evt);
            }
        });

        combousb.setBackground(new java.awt.Color(0, 102, 255));
        combousb.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combousb.setForeground(new java.awt.Color(255, 255, 255));
        combousb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combousb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combousb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combousb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combousbActionPerformed(evt);
            }
        });

        usb.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        usb.setForeground(new java.awt.Color(0, 51, 102));
        usb.setText("Puertos USB :");

        cajaimpresora.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaimpresora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaimpresora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaimpresoraActionPerformed(evt);
            }
        });

        impresora.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora.setForeground(new java.awt.Color(0, 51, 102));
        impresora.setText("Tipo de Impresora:");

        cajaram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaram.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaramActionPerformed(evt);
            }
        });

        ram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ram.setForeground(new java.awt.Color(0, 51, 102));
        ram.setText("Tamaño de RAM : ");

        dd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        dd.setForeground(new java.awt.Color(0, 51, 102));
        dd.setText("Tamaño de Disco Duro :");

        cajadd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajadd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaddActionPerformed(evt);
            }
        });

        impresora1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora1.setForeground(new java.awt.Color(0, 51, 102));
        impresora1.setText("Marca :");

        cajamarca.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamarca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamarcaActionPerformed(evt);
            }
        });

        cajamodelo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamodelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamodeloActionPerformed(evt);
            }
        });

        impresora2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora2.setForeground(new java.awt.Color(0, 51, 102));
        impresora2.setText("Modelo:");

        cajapulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajapulgadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajapulgadas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajapulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajapulgadasActionPerformed(evt);
            }
        });

        pulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        pulgadas.setForeground(new java.awt.Color(0, 51, 102));
        pulgadas.setText("Pulgadas : ");

        lector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        lector.setForeground(new java.awt.Color(0, 51, 102));
        lector.setText("Cuenta Con Lector DVD :");

        combolector.setBackground(new java.awt.Color(0, 102, 255));
        combolector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combolector.setForeground(new java.awt.Color(255, 255, 255));
        combolector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combolector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combolector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combolector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolectorActionPerformed(evt);
            }
        });

        impresora3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora3.setForeground(new java.awt.Color(0, 51, 102));
        impresora3.setText("No.Serie :");

        cajaserie.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaserie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaserie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaserieActionPerformed(evt);
            }
        });

        txtid.setEnabled(false);

        sistemaoperativo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        sistemaoperativo.setForeground(new java.awt.Color(0, 51, 102));
        sistemaoperativo.setText("Sistema operativo :");

        cajasistemaoperativo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajasistemaoperativo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajasistemaoperativo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajasistemaoperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajasistemaoperativoActionPerformed(evt);
            }
        });

        marcaprocesador.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        marcaprocesador.setForeground(new java.awt.Color(0, 51, 102));
        marcaprocesador.setText("Marca procesador : ");

        cajamarcaprocesador.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamarcaprocesador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamarcaprocesador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamarcaprocesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamarcaprocesadorActionPerformed(evt);
            }
        });

        generacionprocesador.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        generacionprocesador.setForeground(new java.awt.Color(0, 51, 102));
        generacionprocesador.setText("Gen procesador : ");

        cajageneracionprocesador.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajageneracionprocesador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajageneracionprocesador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajageneracionprocesador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajageneracionprocesadorActionPerformed(evt);
            }
        });

        marcatargrafica.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        marcatargrafica.setForeground(new java.awt.Color(0, 51, 102));
        marcatargrafica.setText("Marca T Gráfica : ");

        cajamarcatargrafica.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajamarcatargrafica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamarcatargrafica.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamarcatargrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamarcatargraficaActionPerformed(evt);
            }
        });

        tipoups.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        tipoups.setForeground(new java.awt.Color(0, 51, 102));
        tipoups.setText("Tipo Ups : ");

        cajatipoups.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajatipoups.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajatipoups.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajatipoups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatipoupsActionPerformed(evt);
            }
        });

        voltentrada.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        voltentrada.setForeground(new java.awt.Color(0, 51, 102));
        voltentrada.setText("Voltaje de entrada : ");

        cajavoltentrada.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajavoltentrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajavoltentrada.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajavoltentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajavoltentradaActionPerformed(evt);
            }
        });

        voltsalida.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        voltsalida.setForeground(new java.awt.Color(0, 51, 102));
        voltsalida.setText("Voltaje de salida : ");

        cajavoltsalida.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajavoltsalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajavoltsalida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajavoltsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajavoltsalidaActionPerformed(evt);
            }
        });

        cantidadtomas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cantidadtomas.setForeground(new java.awt.Color(0, 51, 102));
        cantidadtomas.setText("Cantidad tomas :");

        cajacantidadtomas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajacantidadtomas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajacantidadtomas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajacantidadtomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajacantidadtomasActionPerformed(evt);
            }
        });

        tipomouse.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        tipomouse.setForeground(new java.awt.Color(0, 51, 102));
        tipomouse.setText("Tipo mouse :");

        cajatipomouse.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajatipomouse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajatipomouse.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajatipomouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatipomouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resolucion)
                            .addComponent(pulgadas)
                            .addComponent(lector)
                            .addComponent(hdmi)
                            .addComponent(usb)
                            .addComponent(dd)
                            .addComponent(ram))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(voltentrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajavoltentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(voltsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cajavoltsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sistemaoperativo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajasistemaoperativo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(marcaprocesador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajamarcaprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tipoups)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajatipoups, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(generacionprocesador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajageneracionprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(marcatargrafica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajamarcatargrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(impresora, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(impresora1)
                                    .addComponent(impresora2)
                                    .addComponent(impresora3)
                                    .addComponent(tipoteclado))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cajatipoteclado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaimpresora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipomouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cantidadtomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cajatipomouse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addComponent(cajacantidadtomas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hdmi)
                            .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usb)
                            .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sistemaoperativo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajasistemaoperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadtomas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajacantidadtomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajamarcaprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipomouse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajatipomouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generacionprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajageneracionprocesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoteclado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajatipoteclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcatargrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajamarcatargrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impresora)
                            .addComponent(cajaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cajatipoups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipoups, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(impresora1)
                                .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajavoltentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impresora2)
                            .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajavoltsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impresora3)
                            .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Caracteristicas", jPanel2);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Datos de Empresa", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14), java.awt.Color.white)); // NOI18N

        ubicacion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(0, 51, 102));
        ubicacion.setText("Ubicacion:");

        cajaubicacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajaubicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaubicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaubicacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Estado:");

        comboestado.setBackground(new java.awt.Color(0, 102, 255));
        comboestado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        comboestado.setForeground(new java.awt.Color(255, 255, 255));
        comboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "ACTIVO", "DESHABILITADO" }));
        comboestado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboestado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboestadoActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Observaciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Text", 2, 14))); // NOI18N

        observacion.setColumns(20);
        observacion.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        observacion.setForeground(new java.awt.Color(0, 51, 102));
        observacion.setRows(5);
        observacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        observacion.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(observacion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cajacustodio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajacustodio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajacustodio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajacustodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajacustodioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Custodio :");

        cajafecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajafecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajafecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajafecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajafechaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Fecha :");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actualizar/actualizar.png"))); // NOI18N
        jButton3.setText("ACTUALIZAR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actualizar/salir.png"))); // NOI18N
        jButton4.setText("SALIR");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ubicacion))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(comboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel10))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cajaubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(cajacustodio)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajafecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajacustodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajafecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Generales", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoActionPerformed
        // TODO add your handling code here:
        int bloqueo = equipo.getSelectedIndex();
       if(bloqueo == 1){
            
            impresora.setVisible(true);
            cajaimpresora.setVisible(true);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
            
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);
            
        }
        if(bloqueo == 2){
            
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(true);
            ram.setVisible(true);
            cajapulgadas.setVisible(false);
            dd.setVisible(true);
            cajadd.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            sistemaoperativo.setVisible(true);
            cajasistemaoperativo.setVisible(true);
            marcaprocesador.setVisible(true);
            cajamarcaprocesador.setVisible(true);
            generacionprocesador.setVisible(true);
            cajageneracionprocesador.setVisible(true);
            marcatargrafica.setVisible(true);
            cajamarcatargrafica.setVisible(true);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
        if(bloqueo == 3){
            
            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            ram.setVisible(true);
            cajapulgadas.setVisible(true);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(true);
            cajaram.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            sistemaoperativo.setVisible(true);
            cajasistemaoperativo.setVisible(true);
            marcaprocesador.setVisible(true);
            cajamarcaprocesador.setVisible(true);
            generacionprocesador.setVisible(true);
            cajageneracionprocesador.setVisible(true);
            marcatargrafica.setVisible(true);
            cajamarcatargrafica.setVisible(true);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);
        }
        if(bloqueo==4){
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(true);
            cajapulgadas.setVisible(false);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(false);
            cajaram.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            sistemaoperativo.setVisible(true);
            cajasistemaoperativo.setVisible(true);
            marcaprocesador.setVisible(true);
            cajamarcaprocesador.setVisible(true);
            generacionprocesador.setVisible(true);
            cajageneracionprocesador.setVisible(true);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
        if(bloqueo == 5){
            
            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
        if(bloqueo == 6){
       
            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
        if(bloqueo == 7){
       
            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
            ram.setVisible(false);
            cajapulgadas.setVisible(true);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(true);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
        if(bloqueo == 8){
       
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(true);
            cajatipoups.setVisible(true);
            voltentrada.setVisible(true);
            cajavoltentrada.setVisible(true);
            voltsalida.setVisible(true);
            cajavoltsalida.setVisible(true);
            cantidadtomas.setVisible(true);
            cajacantidadtomas.setVisible(true);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }
         if(bloqueo == 9){
       
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(false);
            cajatipoteclado.setVisible(false);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(true);
            cajatipomouse.setVisible(true);

        }
         if(bloqueo == 10){
       
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
            ram.setVisible(false);
            cajapulgadas.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajaram.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            tipoteclado.setVisible(true);
            cajatipoteclado.setVisible(true);
            sistemaoperativo.setVisible(false);
            cajasistemaoperativo.setVisible(false);
            marcaprocesador.setVisible(false);
            cajamarcaprocesador.setVisible(false);
            generacionprocesador.setVisible(false);
            cajageneracionprocesador.setVisible(false);
            marcatargrafica.setVisible(false);
            cajamarcatargrafica.setVisible(false);
            tipoups.setVisible(false);
            cajatipoups.setVisible(false);
            voltentrada.setVisible(false);
            cajavoltentrada.setVisible(false);
            voltsalida.setVisible(false);
            cajavoltsalida.setVisible(false);
            cantidadtomas.setVisible(false);
            cajacantidadtomas.setVisible(false);
            tipomouse.setVisible(false);
            cajatipomouse.setVisible(false);

        }

    }//GEN-LAST:event_equipoActionPerformed

    private void cajaresolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaresolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaresolucionActionPerformed

    private void cajatipotecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatipotecladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatipotecladoActionPerformed

    private void combohdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combohdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combohdmiActionPerformed

    private void combousbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combousbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combousbActionPerformed

    private void cajaimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaimpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaimpresoraActionPerformed

    private void cajaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaramActionPerformed

    private void cajaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaddActionPerformed

    private void cajamarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamarcaActionPerformed

    private void cajamodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamodeloActionPerformed

    private void cajapulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajapulgadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajapulgadasActionPerformed

    private void combolectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combolectorActionPerformed

    private void cajaserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaserieActionPerformed

    private void cajaubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaubicacionActionPerformed

    private void comboestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboestadoActionPerformed

    private void cajacustodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajacustodioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajacustodioActionPerformed

    private void cajafechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajafechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajafechaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn = cc.getConnection();
        PreparedStatement pps;
        try {
            pps = cn.prepareStatement("UPDATE articulos SET eq_custodio='"+cajacustodio.getText()+
                "',eq_equipo='"+equipo.getSelectedItem().toString()+
                "',eq_marca='"+cajamarca.getText()+
                "',eq_modelo='"+cajamodelo.getText()+
                "',eq_serie='"+cajaserie.getText()+
                "',eq_resolucion='"+cajaresolucion.getText()+
                "',eq_pulgadas='"+cajapulgadas.getText()+
                "',eq_tamanodisduro='"+cajadd.getText()+
                "',eq_tamanoram='"+cajaram.getText()+
                "',eq_sistemaoperativo='"+cajasistemaoperativo.getText()+
                "',eq_marcaprocesador='"+cajamarcaprocesador.getText()+
                "',eq_genprocesador='"+cajageneracionprocesador.getText()+
                "',eq_marcatargrafica='"+cajamarcatargrafica.getText()+
                "',eq_lectordvd='"+combolector.getSelectedItem().toString()+ 
                "',eq_tipoups='"+cajatipoups.getText()+
                "',eq_voltentrada='"+cajavoltentrada.getText()+
                "',eq_voltsalida='"+cajavoltsalida.getText()+
                "',eq_cantidadtomas='"+cajacantidadtomas.getText()+
                "',eq_tipomouse='"+cajatipomouse.getText()+
                "',eq_tipoteclado='"+cajatipoteclado.getText()+
                "',eq_tipoimpresora='"+cajaimpresora.getText()+
                "',eq_puertohdmi='"+combohdmi.getSelectedItem().toString()+
                "',eq_puertousb='"+combousb.getSelectedItem().toString()+ 
                "',eq_fecharegistro='"+cajafecha.getText()+
                "',eq_ubicacion='"+cajaubicacion.getText()+
                "',eq_estado='"+comboestado.getSelectedItem().toString()+ 
                "',eq_observacion='"+observacion.getText()+   
                "' WHERE eq_serie ='"+txtid.getText()+"'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Actualizados!","CORRECTO",JOptionPane.PLAIN_MESSAGE,icon);
        this.dispose();
       
        } catch (SQLException ex) {
            Logger.getLogger(DatosEditarB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cajasistemaoperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajasistemaoperativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajasistemaoperativoActionPerformed

    private void cajamarcaprocesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamarcaprocesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamarcaprocesadorActionPerformed

    private void cajageneracionprocesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajageneracionprocesadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajageneracionprocesadorActionPerformed

    private void cajamarcatargraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamarcatargraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamarcatargraficaActionPerformed

    private void cajatipoupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatipoupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatipoupsActionPerformed

    private void cajavoltentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajavoltentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajavoltentradaActionPerformed

    private void cajavoltsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajavoltsalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajavoltsalidaActionPerformed

    private void cajacantidadtomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajacantidadtomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajacantidadtomasActionPerformed

    private void cajatipomouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatipomouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatipomouseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEditarB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEditarB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cajacantidadtomas;
    public static javax.swing.JTextField cajacustodio;
    public static javax.swing.JTextField cajadd;
    public static javax.swing.JTextField cajafecha;
    public static javax.swing.JTextField cajageneracionprocesador;
    public static javax.swing.JTextField cajaimpresora;
    public static javax.swing.JTextField cajamarca;
    public static javax.swing.JTextField cajamarcaprocesador;
    public static javax.swing.JTextField cajamarcatargrafica;
    public static javax.swing.JTextField cajamodelo;
    public static javax.swing.JTextField cajapulgadas;
    public static javax.swing.JTextField cajaram;
    public static javax.swing.JTextField cajaresolucion;
    public static javax.swing.JTextField cajaserie;
    public static javax.swing.JTextField cajasistemaoperativo;
    public static javax.swing.JTextField cajatipomouse;
    public static javax.swing.JTextField cajatipoteclado;
    public static javax.swing.JTextField cajatipoups;
    public static javax.swing.JTextField cajaubicacion;
    public static javax.swing.JTextField cajavoltentrada;
    public static javax.swing.JTextField cajavoltsalida;
    private javax.swing.JLabel cantidadtomas;
    public static javax.swing.JComboBox comboestado;
    public static javax.swing.JComboBox combohdmi;
    public static javax.swing.JComboBox combolector;
    public static javax.swing.JComboBox combousb;
    private javax.swing.JLabel dd;
    public static javax.swing.JComboBox equipo;
    private javax.swing.JLabel generacionprocesador;
    private javax.swing.JLabel hdmi;
    private javax.swing.JLabel impresora;
    private javax.swing.JLabel impresora1;
    private javax.swing.JLabel impresora2;
    private javax.swing.JLabel impresora3;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lector;
    private javax.swing.JLabel marcaprocesador;
    private javax.swing.JLabel marcatargrafica;
    public static javax.swing.JTextArea observacion;
    private javax.swing.JLabel pulgadas;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel resolucion;
    private javax.swing.JLabel sistemaoperativo;
    private javax.swing.JLabel tipomouse;
    private javax.swing.JLabel tipoteclado;
    private javax.swing.JLabel tipoups;
    public static javax.swing.JTextField txtid;
    private javax.swing.JLabel ubicacion;
    private javax.swing.JLabel usb;
    private javax.swing.JLabel voltentrada;
    private javax.swing.JLabel voltsalida;
    // End of variables declaration//GEN-END:variables
}
